version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64

archives:
  - formats: [tar.gz]
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    homepage: https://mygento.com
    description: Workplace CLI helps developers manage projects
    maintainer: NT <nikita@mygento.com>
    license: AGPL-3.0
    vendor: Mygento
    formats:
    - deb
